title: Eme's Blog
author: mjbenitez
email: mjbenitez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog created in FrontEnd Foxes Bootcamp with GitHub Pages

# social links
twitter_username: mj_benitez # DO NOT include the @ character, or else the build will fail!
github_username:  mjbenitez # DO NOT include the @ character, or else the build will fail!

# theme
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
